### ISSUE TITLE
Submit button should report correct status

### ISSUE THREAD

**Issue by papajohn** [data-8/Gofer-Grader#16]
I installed the submit extension and clicked submit in an example notebook. The pop-up told me that my notebook had been submitted, even though I wasn't running the autograder server. It seems that the button should await a positive response before showing such a message.

**Comment by vipasu** [comment]
Thanks for pointing this out. After some discussion, we changed the extension to simply notify the student that their submission has been saved and is being graded. This notification only occurs when their notebook is actually saved (e.g. when the auto grading server runs properly)
